name: radio_otherway
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_dynamic_links: ^5.0.15
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.1
  google_sign_in: ^6.0.0
  http: 0.13.5
  overlay_support: ^2.1.0
  twitter_login: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
