name:
  Send Reminders
on:
  # Every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
jobs:
  reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Cache outstanding events
        run: curl -X GET https://external.fergl.ie/api/cron/reminders
