name:
  Cache Events
on:
  # Every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache outstanding events
        run: curl -X GET https://otherway.fergl.ie/api/cron/cache
