name:
  Cache Jobs
on:
  # Every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Cache outstanding events
        run: curl -X GET https://external.dev.fergl.ie:3000/api/cron/cache
